"""fix apartment model

Revision ID: 5171607a5da2
Revises: b3502cfa1303
Create Date: 2024-01-30 18:13:12.148616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5171607a5da2'
down_revision = 'b3502cfa1303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartment', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartment', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
